name: Build AIG Proposal

on:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: AIG_proposal.tex
          working_directory: AIG_paper
      - uses: actions/upload-artifact@v4
        with:
          name: AIG_proposal
          path: AIG_paper/AIG_proposal.pdf
